services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse-server
    ports:
      - "${CLICKHOUSE_PORT_HTTP}:8123"
      - "${CLICKHOUSE_PORT_NATIVE}:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile: { soft: 262144, hard: 262144 }
    healthcheck:
      test: ["CMD", "clickhouse-client", "-q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: genostream-api
    ports:
      - "${API_PORT}:8000"
    depends_on:
      clickhouse-server:
        condition: service_healthy
    environment:
      - host=clickhouse-server
      - db=${CLICKHOUSE_DB}
      - user=${CLICKHOUSE_USER}
      - password=${CLICKHOUSE_PASSWORD}
    env_file:
      - .env

volumes:
  clickhouse_data: